### ISSUE TITLE
Touch screen input is rotated 90 degrees relative to screen

### ISSUE THREAD

**Issue by DavidCWGA** [cawilliamson/ansible-gpdpocket#117]
The position you touch the screen is actually rotated 90 degrees relative to what is displayed on it. Presumably this is related to the portrait screen issue, and also the cause of #112, it's not slow, you're actually not tapping where you think you are.

A video demonstration of the problem: https://youtu.be/1mFardgh0r8

**Comment by icebal** [comment]
please provide the following information:

1. distro and desktop environment used
2. you have ran sudo gpd-update and rebooted
3. any errors reported from the update?
3. is this affected everywhere? have you tried a different DE/WM?
4. does sudo gpd-rotate fix the touhsreen rotation issue?

**Comment by DavidCWGA** [comment]
1. Debian 9, Gnome 3.
2. Yes.
3. No.
4. I haven't tried a different DE.
5. gpd-rotate fails: "xinput: not found", but after installing xinput, it DOES fix the problem, but the problem comes back after a reboot.

**Comment by nexus511** [comment]
That is strange. If xinput is missing, it does not work (that is right). I think that the scripts are missing a dependency on that.

But it should be there after you installed it. Can you check, if gpd-rotate is running as a service?

Try

```
ps aux | grep gpd-rotate
```

and

```
systemctl status gpd-rotate.service
```

**Comment by psrb191921** [comment]
Some kind of the same issue in ubuntu 17.10 with gnome, I should run gpd-rotate after each sleep/or screen lock (win+L)
Also touch events seems to position cursor for the first touch and actually click for the second one, thats annoying

**Comment by nexus511** [comment]
Well. The reason is that the gpd-rotate service is not running properly on your device.

I have not taken a look at 17.10 but it works for 16.04.3 and 17.04 (at least on my devices). So I guess the service just crashes at some point and someone should take a look at it and fix that.

**Comment by DavidCWGA** [comment]
gpd-rotate is not running.

````
$ systemctl status gpd-rotate.service
● gpd-rotate.service - GPD Display Rotation Service
   Loaded: loaded (/etc/systemd/system/gpd-rotate.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2017-08-24 23:58:26 PDT; 19h ago
  Process: 853 ExecStart=/usr/local/sbin/gpd-rotate --screen=${SCREEN} --touchscreen=${TOUCHSCREEN} (code
 Main PID: 853 (code=exited, status=0/SUCCESS)
````

**Comment by psrb191921** [comment]
Same on ubuntu gnome and 17.04

**Comment by nexus511** [comment]
I have not yet looked into the script but having plans to review it. I have seen several crashes of the service and other odd behavior. Maybe it needs some polish to provide a bit more stability.

**Comment by nexus511** [comment]
Ah, basically a good idea to take a look at the script. It is basically run once on by systemd and basically does not run as a service.

It also uses some sleep values to wait for things getting ready. That basically explains the different (more or less) odd random display rotations I have been experiencing. While this solutions might work in most cases it also might cause some trouble in others. So this is basically a good point to start from but I guess I will take a look at a more durable approach next week based on the existing script.

So, what you could do for now is just start the script again after you X11 has come up by calling

```
/usr/local/sbin/gpd-rotate --screen=1 --touchscreen=1
```

It might help you out for now.

If calling the above snippet manually works for you, please let me know. That would mean that we are on the right track here and I could be working on that. I doubt that I will come up with a solution before monday though.

PS.: What @cawilliamson is trying to archive here is a very time consuming task and he does an awesome job on that. So it's basically normal that things tend to break or behave odd on different platforms. I guess he is having a hard day in keeping track of all the stuff happening here.

**Comment by psrb191921** [comment]
I've back to using respin project and budgie as it has absolutly no issues (and no support either :) why not copy some stuff that just work? Gnome is still unusable which is sad, as gnome is the best desktop for touch screen

**Comment by nexus511** [comment]
@psrb191921 I am currently on a project that just delivers working ISO images and updates via APT. You might take a look at this project here: http://apt.nexus511.net/

All the work is based on this project here, but aims to only support Ubuntu based images to gain a bit more stability.

Anyway. I consider this project here as a good base to gain a grip on multiple distributions at once, so it is worth to keep it running.

**Comment by cawilliamson** [comment]
@nexus511 To tell you the truth - I'm getting tired of trying to support so many distros.

The Linux distros are far too fragmented to allow this project to remain viable. I don't have the amount of time it takes to keep this stuff working available at this point.

Will have to see how things go but I'm very supportive of your approach. Eventually this stuff needs to be all in the kernel or the distro one way or another.

**Comment by nexus511** [comment]
@cawilliamson Yeah, well. My job has somewhat been porting Linux and now Android for different devices and to be honest this does not come for me as a surprise at all.

It is nearly impossible to support more than one or two distributions with the same baseline (and even this is hard to manage). Anyway: You are doing an awesome job here and I would like to encourage you to continue this for at lease one distribution. If I keep working on the Ubuntu based tree and merge your baseline into my packages, we will be able to keep two distributions running.

So if you like to hear my opinion: Maintaining one distribution is more a single person could do. I guess I will reach the same point only on the Ubuntu track in near future. As your repository is still the most advanced approach to reach out to so many distributions it would be really bad if your project dies. Maybe you could stick on working for the distribution you like most and leave the others to people that are going to maintain their beloved distribution on their own. I guess that would be the best approach and it would help a community of maintainers to learn from each other.

So I hope you keep this going.

PS.: Just to give you a hint about the workload for only one distribution: it basically took me the whole last week about (10h*6d) to get the Ubuntu package tree working. So I really have a feeling what your workload would look like, if you continue your track.

**Comment by icebal** [comment]
I'm all for working on the arch side, gives me a chance to learn the
ansible side of things :) your repo, your call, I'm just here to make this
work as best as possible. Without your repo I'd still be stuck on Windows
10 on the pocket :'(

On Aug 26, 2017 3:14 PM, "nexus511" <notifications@github.com> wrote:

@cawilliamson <https://github.com/cawilliamson> Yeah, well. My job has
somewhat been porting Linux and now Android for different devices and to be
honest this does not come for me as a surprise at all.

It is nearly impossible to support more than one or two distributions with
the same baseline (and even this is hard to manage). Anyway: You are doing
an awesome job here and I would like to encourage you to continue this for
at lease one distribution. If I keep working on the Ubuntu based tree and
merge your baseline into my packages, we will be able to keep two
distributions running.

So if you like to hear my opinion: Maintaining one distribution is more a
single person could do. I guess I will reach the same point only on the
Ubuntu track in near future. As your repository is still the most advanced
approach to reach out to so many distributions it would be really bad if
your project dies. Maybe you could stick on working for the distribution
you like most and leave the others to people that are going to maintain
their beloved distribution on their own. I guess that would be the best
approach and it would help a community of maintainers to learn from each
other.

So I hope you keep this going.

PS.: Just to give you a hint about the workload for only one distribution:
it basically took me the whole last week about (10h*6d) to get the Ubuntu
package tree working. So I really have a feeling what your workload would
look like, if you continue your track.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/cawilliamson/ansible-gpdpocket/issues/117#issuecomment-325159382>,
or mute the thread

**Comment by DavidCWGA** [comment]
> /usr/local/sbin/gpd-rotate --screen=1 --touchscreen=1
> If calling the above snippet manually works for you, please let me know.

Yes, running this after waking from sleep solves the problem.

**Comment by nexus511** [comment]
@DavidCWGA You might take a look at #134 

I currently do not have the time to create a PR, so if anyone does, it would be great. This would be the proper solution to tell X11 that there should be a rotation and that it should always happen for the internal screen.
