### ISSUE TITLE
No wlan channel 13

### ISSUE THREAD

**Issue by enthusi** [cawilliamson/ansible-gpdpocket#133]
Hi,
it appears that the wlan does not recognize SSIDs at channel 13 (maybe others too?).
Can anyone confirm that with a recent build?

**Comment by Herst** [comment]
Is channel 13 one of these channels only available in some regions?

**Comment by enthusi** [comment]
Yes, apparently it is not used in the North US (didn't know that) but here (Germany) it is ;-)
Is that a simple enough fix?
https://en.wikipedia.org/wiki/List_of_WLAN_channels

**Comment by Herst** [comment]
The region needs to be set somewhere, but I have no idea where, it might depend on the driver used.

**Comment by cawilliamson** [comment]
@enthusi This is a distro-specific setting and unfortunately out of scope for the Ansible playbooks since I can't know where you live! :(

I would recommend looking at your distro documentation since what you're looking for will be available there.

I don't believe this is an issue specific to this particular chipset.

**Comment by Herst** [comment]
Please feel free to share any findings on this though.
