### ISSUE TITLE
Battery power monitor not displaing correct on Ubuntu 16.04.3

### ISSUE THREAD

**Issue by adam3234** [cawilliamson/ansible-gpdpocket#135]
The battery is nearly fully charged but it is showing about 50% charged.
![20170828_195942](https://user-images.githubusercontent.com/31406169/29770999-fe634bc6-8c34-11e7-8324-78fa5bc257bb.jpg)

![20170828_200438](https://user-images.githubusercontent.com/31406169/29771035-3281f04c-8c35-11e7-88fc-c4648cb44ae0.jpg)

 Also, it appears to be showing that there are 2 batteries?
![20170828_200417](https://user-images.githubusercontent.com/31406169/29771074-5f5ce75c-8c35-11e7-804e-52e28c5183be.jpg)

**Comment by greg-the-maker** [comment]
There's a fix here. I'm not sure if it will work on Ubuntu though. I have the same issue but havne't had a try at it yet.

https://www.reddit.com/r/GPDPocket/comments/6w0j73/i_fixed_displaying_second_0_battery_in/

**Comment by nexus511** [comment]
A new Kernel fixes this issue.

This should be fixed by the pull request #126 once merged.

**Comment by cawilliamson** [comment]
Yeah - you need to run a `sudo gpd-update` - this is known and it's because you're running the funky BIOS.

Other than shipping another huge binary in the git repo (which I would rather not do) there isn't a whole lot I can do about this. The bootstrap kernel is to bootstrap you - not to run forever and ever. :)
