### ISSUE TITLE
No hibernate support (suspend-to-disk)

### ISSUE THREAD

**Issue by sm0kew0n** [cawilliamson/ansible-gpdpocket#25]
Hibernate doesn't complete in Debian 9.1.0
Kernel = 4.13.0-rc3-jwrdegeode
Ansible = bootstrap-system

**Comment by Herst** [comment]
What exactly fails, going into hibernation or waking up?

**Comment by sm0kew0n** [comment]
Entering hibernation fails to complete. Power lights remain on, no response to keyboard, hard reset required.

**Comment by cawilliamson** [comment]
Hey @sm0kew0n - I'm aware of this - it doesn't complete on ANY distro at the moment and this may well be a kernel related issue but I am investigating this and I'll work with Hans if any kernel patching does need to happen.

**Comment by sm0kew0n** [comment]
Appreciate your efforts, thanks.

If it's any help (not a coder!) pm_test passed [freezer] [device] [platform] but failed [processors] [core] when /sys/power/disk running as [platform]

I can do some more tests and try to capture fail logs if it helps?

**Comment by cawilliamson** [comment]
To be honest - past a brief look I haven't done a lot of research around pm / hibernation.

I suspect it may be a kernel issue (which means I will have to talk to Hans and see what he says) but I'm a bit tied up working on getting Fedora ISOs bootstrapped for those with err... slightly less taste in distros than ourselves! ;)

I'll update this once I get a chance to have a proper look.

**Comment by cawilliamson** [comment]
Ok - I've talked to Hans about this and his recommendation (which does make sense in my view) is not to use hibernation at all if you can avoid it since it will kill the emmc storage quickly by writing 8GB of RAM to it every time you hibernate - does make sense.

However! I think the real problem is that suspend doesn't work properly for a lot of folks recently and the system is waking up (potentially due to a touchscreen driver issue.) As such - I've asked Hans to look in to that to see if there is anything he can do from his side to resolve the issue. I know he has written a lot of code regarding the touchscreen so perhaps it's something he can resolve but sadly - there's not a lot I can do about it from my side.

What I'll do is add an update to the README file to list it as a known issue and will update the README once it's fixed.

Going to close this one for now though since, as I mentioned, this is not something I can fix or work around - it's really a kernel level fix.
