### ISSUE TITLE
xmonad font and screen issues

### ISSUE THREAD

**Issue by brittAnderson** [cawilliamson/ansible-gpdpocket#50]
Please do not spend time on this; just share whatever pops into your head. This is a very niche issue. I am successfully using your playbooks. When I run xmonad as the display manager the fonts for many applications are huge (e.g. emacs or using dmenu (from suckless-tools) to select applications) - taking up a third to half the screen. 

1. Do you know what might be getting set to cause that? I saw something similar when trying to run lubuntu desktop that did not happen on xubuntu desktop even though no settings were changed.

2. If using a second monitor the gpdpocket treats both monitors as one extended monitor instead of two workspaces, which is the xmonad default. I can't force this behavior to change, and the size of fonts and menus is really not useable. Note that under xubuntu everything is fine because I can set the scaling and size with for the second monitor with xrandr and there an extended monitor instead of separate workspaces is not really an issue.

Xubuntu/xfce is entirely usable for me. Being able to use my familiar tiling display manager would be a bonus, but is not at all necessary. If you have some hints for things to try, I may play around some more. If not, I will just close this issue. 

Afterthought: any word on whether people have gotten i3 to work? I just find with the small screens that being able to use the keyboard to full screen and swap and tile is really handy.

Cheers,

**Comment by cawilliamson** [comment]
Hey - firstly, thanks for the donation! Much appreciated!

As for xmonad / i3 - is this still happening with the latest ansible playbooks?

I ask because I did experience this in i3 and I added a fix - well, simply put I removed the following:

```
/etc/X11/xorg.conf.d/30-monitor.conf
/etc/X11/xorg.conf.d/80-screen.conf
/etc/X11/xorg.conf.d/89-screen.conf
/etc/X11/xorg.conf.d/90-monitor.conf
```

Though the latest ansible playbook should do this for you - I'm planning to reinstall Arch Linux very shortly and install i3 on that so I'll soon find out if there are problems there (and fix them if so!)

**Comment by brittAnderson** [comment]
Ran gpd-update. Had to run again with the --limit command, and now everything works perfectly. Awesome

**Comment by cawilliamson** [comment]
With the --limit command? Why?

Was something else broken?

**Comment by brittAnderson** [comment]
The update required downloading and compiling a new kernel. I was inattentive and the gpd fell asleep. When I woke it I saw that something had failed, and there was a helpful suggestion on the screen to retry with the limit option. In other settings, other computers, I have occasionally had things fail with kernel compiles (maybe using up all the memory?). I thought it had less to do with the script and something more specific to the compile process and/or the sleep. Since it ran quickly and flawlessly when gpd-update repeated, I took that as confirmation that it wasn't a script issue (it had managed to download and compile the kernel already as it did not need to repeat those steps). That's all I can offer at this point.

**Comment by cawilliamson** [comment]
Ah - the problem is - it will *only* compile a new kernel if the kernel source code is updated.

As such - it's likely that you're not running the latest kernel at this point. That having been said - a new kernel source update was pushed today so it could be a good time to grab the latest kernel - I would recommend disabling sleep mode though whilst it's compiling! I'll see if there's something I can do to disable sleep for the duration of the compile.

Thanks for the update though - very helpful! :)

**Comment by brittAnderson** [comment]
I note that I am skipping the kernel update option and stuck on 4.13rc2 though it looks like Hans Repo is up to rc5. The playbook runs, but it skips the get kernel update and compile step. Is there a way to "clean" so I can try again?

**Comment by Herst** [comment]
Hm… the history of Hans his repository changes quite often (because of automated rebases) and my change in #39 makes it so that all the history is culled, maybe this leads to some situation where a change in the repository isn't detected any more, what do you think @cawilliamson?
