### ISSUE TITLE
Unable to create iso from Solus

### ISSUE THREAD

**Issue by Awwkaw** [cawilliamson/ansible-gpdpocket#70]
I'm trying to create a bootable iso from Solus. This however fails, and i think it does so when trying to run the reload command.

The only place my grep could find the reload command was in the callback_plugins/human_log.py file.

I tried editing it out, but couldn't (even after chmod 777 human_log.py)

Picture of the errorlog below

I've tried to create both an antergos, an arch and a solus iso. all give the same result.
![image](https://user-images.githubusercontent.com/25682700/29481573-19f69460-8483-11e7-8d02-06aab5e134ca.png)

**Comment by cawilliamson** [comment]
Bootstrapping from Solus isn't supported and is unlikely to ever be supported.

Fire up a VM with one of the listed supported distros and you shouldn't have any trouble.

**Comment by RankoKohime** [comment]
Out of curiosity, what is missing from Solus that prevents it from being a source or destination OS for this project?

**Comment by cawilliamson** [comment]
Nothing prevents it from being used as a source or destination - I just don't wish to spend the time adding support for it.

You're more than welcome to put in the work and submit a pull request though and I'll happily accept it. :)

**Comment by Awwkaw** [comment]
I'd love to spend the time doing this, i just don't really know any of the tools.

The whole reason i started the issue was, that it actually did work a couple of days ago.
I bootstrapped both arch and antergos from a Solus PC. But then, after pulling to update the scripts (i saw that there had been a bug with the antergos iso) it stopped working.

If it wasn't supposed to work there was no reason for the bug XD.

**Comment by cawilliamson** [comment]
If you just need a build an ISO you can use a few options:

1.) Docker
2.) KVM
3.) Virtualbox
4.) Another system
5.) A LiveCD/LiveDVD/LiveUSB environment running on your main system

I know it sucks that you can't just build directly from your distro but yeah - in short, none of the package install steps will work on Solus since it doesn't use apt, pacman, portage or yum.

**Comment by Awwkaw** [comment]
Thanks, but i ment i don't have the skill to add solus support XD.

That might be half a lie, when i said that i'd sucessfully bootstrapped arch and antergos from solus, i meant that i'd added the lines:

`elif [ -f /usr/bin/eopkg ]; then`
`  eopkg ur`
 ` eopkg it ansible git 
`

to the install part of both bootstrap-iso.sh and bootstrap-system.sh, this worked for an earlier version of Solus (i couldn't get it to bootstrap solus, but i did manage to get (as of now untested) bootstrap.iso files from arch and antergos.

However this broke when i updated the ansible scripts (when i succeded bootstrap-iso still called bootstrap-system, but as far as i can tell it doesn't anymore)

**Comment by cawilliamson** [comment]
Tell you what - I'll look in to this as time permits as a host build system only since it's likely not much work.

I wont be supporting Solus as a GPD distro any time soon though but again, I'm open to PRs if anyone is interested.

The reason I don't support Solus is because only one person has asked about it - you! It's just not worth the effort to support something like that unless there's more interest or absolutely ALL mainstream distros are working flawlessly (which, of course, they aren't!)

**Comment by RankoKohime** [comment]
I forked and did a few commits to get the basic stuff working, though I ran into a small brick wall around power, since i2c-tools is not in Solus, and it's damn difficult to track it down to submit a proper package request to the Solus team.  i2c-tools seems to be in a bit of limbo at the moment.

Another snag I've found is that ansible is behaving differently on Solus than it is on my Arch box.  On my Arch box running:
`ansible localhost -m setup -a 'filter=ansible_distribution'`
produces output, but on Solus, it wants to connect via ssh for some reason.

Anyway, I'll submit a PR for the changes I've done thus far, it's a start anyway.

**Comment by Awwkaw** [comment]
I've opened a package request for i2c tools from the source found here: [https://sources.debian.net/src/i2c-tools/3.1.2-3/](url)

**Comment by RankoKohime** [comment]
[Link](https://dev.solus-project.com/T4366) to the relevant issue on Solus bug tracker.

Awwkaw, I assume you meant by "in the Solus repositories" that you added it to the bug tracker?  As I don't see it in the repo and the package request is still open.

**Comment by cawilliamson** [comment]
Folks - I'm going to close this one off for now but feel free to submit any code via a pull request (as you have done previously.) 👍
