### ISSUE TITLE
WLAN not working on xubuntu 16.04.3

### ISSUE THREAD

**Issue by nexus511** [cawilliamson/ansible-gpdpocket#77]
I am currently working on getting the bootstrapping running for xubuntu images. The outcome looks promising as this does not have several of the glitches seen on the ubuntu image.

For now, the Wifi does not work. It can scan for accesspoints, connect to them, retrieves an IP address and routing information via DHCP but is not able to communicate along the network in any other way.

I will try to bring up a fix for this as soon as I have understood the origin of this behavior.

**Comment by cawilliamson** [comment]
A lot of the ansible playbook relies on ansible_distribution - I could check to confirm that Xubuntu doesn't claim to be something other than 'Ubuntu' (like Antergos and Manjaro claim not to be 'Archlinux'.)

As for the wifi - does /etc/resolv.conf end up in a broken state perhaps? May be worth throwing the following in there to check:

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

Hopefully that helps!

Awesome work on this though - it's great to have pull requests coming instead of an onslaught of issues! 👍

**Comment by nexus511** [comment]
Yes. Already checking stuff in there. I already found that resolv.conf does not look right but it should also basically be set by network-manager though.

Anyway. I think that should be not to hard to get it fixed.

**Comment by nexus511** [comment]
Has been an issue with resolv.conf, yes. This should be fixed with my pull-request.
