### ISSUE TITLE
Full audit of all shell scripting

### ISSUE THREAD

**Issue by cawilliamson** [cawilliamson/ansible-gpdpocket#88]
Ultimately the purpose of this ticket is to track my work towards removing as much "shell" steps as possible from Ansible. Typically where shell is used - it's because I needed a quick 'N dirty hack to get something working and certainly isn't maintainable.

@Herst - your opinion is extremely valuable on this stuff too - where shell really *is* needed - best practice scripting (preferably shell independent - i.e. POSIX compliant) would be best rather than forcing bash everywhere.

**Comment by Herst** [comment]
I planned on looking through all the shell stuff already for quite some time, but never managed to actually do it. I came across the one pull request rather randomly. (Had I done it earlier maybe the `bash`/`dash` issue would have been noticed earlier, oh well. :/)

Please tell me once all the remaining `shell:` stuff is here to stay so I will have a look at it but from a quick glance there is hardly anything complicated being done and most issues have to with best practises with quoting rather than real issues, e.g. 
```sh
cp -f /usr/src/linux-jwrdegoede/arch/x86/boot/bzImage /boot/vmlinuz-$(ls -t /lib/modules/ |head -n 1)
```
This will break if there is a file with a space in it's name (e.g. if there is `/lib/modules/foo\ bar` which is the newest one then the line will turn into the equivalent `cp -f '/usr/src/linux-jwrdegoede/arch/x86/boot/bzImage' '/boot/vmlinuz-foo' 'bar'` [three arguments]) but that's unlikely to happen.
